### ISSUE TITLE
Bost converter isn't needed.

### ISSUE THREAD

**Issue by Kalrkloss** [RamboRogers/rfhunter#1]
The AD8317 itself can work from 3.0 to 5.5V.
The board you're using has a 5V regulator (78L05), that needs an input voltage of at least 7V.
If you replace the voltage regulator by a jumper wire, you can omit the boost converter, and also save some power.
![AD8317mod](https://github.com/user-attachments/assets/284cec82-402f-4bd0-aa15-da415e896d0d)

**Comment by EspressoTini** [comment]
Was just going to say the same, 9v not needed.  This chip would also be sweet on a credit card size pcb, coin cell battery, and LEDs for the signal stregth, for portability.  Maybe the antenna could be pcb too

**Comment by RamboRogers** [comment]
Thats a cool idea!  I don't know the underlying design of the board, I just use it as a signal source.

**Comment by RamboRogers** [comment]
Added note to README

**Comment by lukeswitz** [comment]
I’m curious why this issue is closed. 

Wow, this thing is huge! Its like a 90’s cordless phone. This could all be done on a single layer. Anyhow- the problem is indeed an issue from any objective electrical perspective. But if you’re ok with it “just working” then close away. 

Removing the unit and jumping those pads indeed saves power and eliminates the need for the boost controller (that’s very prone to blowing the pot and worse from a simple search). Eliminating a point of failure and decreasing power consumption - win/win. At least link a reliable step-up to 9v or something. 

Link to this closed issue in the readme perhaps. Good luck!
